// Full current-season Premier League player pool for the Draft Tracker,
// sourced from the official Fantasy Premier League API
// (fantasy.premierleague.com/api/bootstrap-static/). Static snapshot, not
// a live fetch -- that endpoint doesn't allow cross-origin requests from a
// browser, so this is fetched server-side once and committed, matching
// content.js's pattern for the other rounds' static data. Re-run the same
// fetch (see the project's session notes) to refresh for transfers.
// `price` is now_cost/10 (FPL's own convention -- e.g. 60 means GBP6.0m),
// used by the Draft Tracker's GBP100m budget.
window.PL_PLAYERS = [{id:1,name:"David Raya Martín",team:"Arsenal",teamShort:"ARS",pos:"GKP",price:6},
{id:2,name:"Kepa Arrizabalaga Revuelta",team:"Arsenal",teamShort:"ARS",pos:"GKP",price:5},
{id:3,name:"Illan Meslier",team:"Arsenal",teamShort:"ARS",pos:"GKP",price:5},
{id:4,name:"Gabriel dos Santos Magalhães",team:"Arsenal",teamShort:"ARS",pos:"DEF",price:8},
{id:5,name:"Jurriën Timber",team:"Arsenal",teamShort:"ARS",pos:"DEF",price:6.5},
{id:6,name:"William Saliba",team:"Arsenal",teamShort:"ARS",pos:"DEF",price:6},
{id:7,name:"Myles Lewis-Skelly",team:"Arsenal",teamShort:"ARS",pos:"MID",price:5.5},
{id:8,name:"Riccardo Calafiori",team:"Arsenal",teamShort:"ARS",pos:"DEF",price:5.5},
{id:9,name:"Piero Hincapié",team:"Arsenal",teamShort:"ARS",pos:"DEF",price:5.5},
{id:10,name:"Benjamin White",team:"Arsenal",teamShort:"ARS",pos:"DEF",price:5.5},
{id:11,name:"Cristhian Mosquera",team:"Arsenal",teamShort:"ARS",pos:"DEF",price:5.5},
{id:12,name:"Bukayo Saka",team:"Arsenal",teamShort:"ARS",pos:"MID",price:9.5},
{id:13,name:"Declan Rice",team:"Arsenal",teamShort:"ARS",pos:"MID",price:7.5},
{id:14,name:"Eberechi Eze",team:"Arsenal",teamShort:"ARS",pos:"MID",price:6.5},
{id:15,name:"Martin Ødegaard",team:"Arsenal",teamShort:"ARS",pos:"MID",price:6.5},
{id:16,name:"Noni Madueke",team:"Arsenal",teamShort:"ARS",pos:"MID",price:6.5},
{id:17,name:"Mikel Merino Zazón",team:"Arsenal",teamShort:"ARS",pos:"MID",price:6},
{id:18,name:"Gabriel Martinelli Silva",team:"Arsenal",teamShort:"ARS",pos:"MID",price:6.5},
{id:19,name:"Martín Zubimendi Ibáñez",team:"Arsenal",teamShort:"ARS",pos:"MID",price:5.5},
{id:20,name:"Max Dowman",team:"Arsenal",teamShort:"ARS",pos:"MID",price:5.5},
{id:22,name:"Ethan Nwaneri",team:"Arsenal",teamShort:"ARS",pos:"MID",price:5.5},
{id:23,name:"Fábio Ferreira Vieira",team:"Arsenal",teamShort:"ARS",pos:"MID",price:5.5},
{id:24,name:"Reiss Nelson",team:"Arsenal",teamShort:"ARS",pos:"MID",price:5.5},
{id:25,name:"Viktor Gyökeres",team:"Arsenal",teamShort:"ARS",pos:"FWD",price:7.5},
{id:26,name:"Kai Havertz",team:"Arsenal",teamShort:"ARS",pos:"FWD",price:7.5},
{id:27,name:"Gabriel Fernando de Jesus",team:"Arsenal",teamShort:"ARS",pos:"FWD",price:6},
{id:452,name:"Bruno Guimarães Rodriguez Moura",team:"Arsenal",teamShort:"ARS",pos:"MID",price:7},
{id:557,name:"Christos Tzolis",team:"Arsenal",teamShort:"ARS",pos:"MID",price:6.5},
{id:28,name:"Emiliano Martínez Romero",team:"Aston Villa",teamShort:"AVL",pos:"GKP",price:5},
{id:29,name:"Marco Bizot",team:"Aston Villa",teamShort:"AVL",pos:"GKP",price:4.5},
{id:30,name:"Lucas Digne",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4.5},
{id:31,name:"Ezri Konsa Ngoyo",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4.5},
{id:32,name:"Matty Cash",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4.5},
{id:33,name:"Tyrone Mings",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4.5},
{id:34,name:"Pau Torres",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4.5},
{id:35,name:"Lamare Bogarde",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5},
{id:36,name:"Ian Maatsen",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4.5},
{id:37,name:"Victor Lindelöf",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4.5},
{id:38,name:"Andrés García",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4},
{id:39,name:"Kosta Nedeljkovic",team:"Aston Villa",teamShort:"AVL",pos:"DEF",price:4},
{id:41,name:"Emiliano Buendía Stati",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:6},
{id:44,name:"Leon Bailey",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5.5},
{id:45,name:"John McGinn",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5.5},
{id:46,name:"Ross Barkley",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5},
{id:47,name:"Boubacar Kamara",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5},
{id:48,name:"Amadou Onana",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5},
{id:49,name:"Samuel Iling-Junior",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5},
{id:50,name:"Bradley Burrowes",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:4.5},
{id:51,name:"George Hemmings",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:4.5},
{id:52,name:"Alysson Edward Franco da Rocha dos Santos",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5},
{id:53,name:"Johan Manzambi",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:6},
{id:54,name:"Joao Gomes",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:5.5},
{id:55,name:"Ollie Watkins",team:"Aston Villa",teamShort:"AVL",pos:"FWD",price:8},
{id:56,name:"Tammy Abraham",team:"Aston Villa",teamShort:"AVL",pos:"FWD",price:5.5},
{id:160,name:"Alejandro Garnacho Ferreyra",team:"Aston Villa",teamShort:"AVL",pos:"MID",price:6},
{id:582,name:"Brian Madjo",team:"Aston Villa",teamShort:"AVL",pos:"FWD",price:5.5},
{id:57,name:"Đorđe Petrović",team:"Bournemouth",teamShort:"BOU",pos:"GKP",price:4.5},
{id:58,name:"Fraser Forster",team:"Bournemouth",teamShort:"BOU",pos:"GKP",price:4},
{id:59,name:"Will Dennis",team:"Bournemouth",teamShort:"BOU",pos:"GKP",price:4},
{id:60,name:"James Hill",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:5.5},
{id:61,name:"Adrien Truffert",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:5.5},
{id:62,name:"Bafodé Diakité",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:5},
{id:63,name:"Veljko Milosavljevic",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:5},
{id:64,name:"Adam Smith",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:4.5},
{id:65,name:"Julián Araujo Zúñiga",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:4.5},
{id:66,name:"Julio Soler Barreto",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:4},
{id:67,name:"Rayan Vitor Simplício Rocha",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:6.5},
{id:68,name:"Marcus Tavernier",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:6},
{id:69,name:"Alex Scott",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:6},
{id:70,name:"Justin Kluivert",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:6},
{id:71,name:"Lewis Cook",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:5},
{id:72,name:"Ben Gannon-Doak",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:5},
{id:73,name:"Tyler Adams",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:5},
{id:74,name:"David Brooks",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:5},
{id:75,name:"Ryan Christie",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:5},
{id:76,name:"Alex Tóth",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:5},
{id:77,name:"Amine Adli",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:5},
{id:78,name:"Junior Kroupi",team:"Bournemouth",teamShort:"BOU",pos:"MID",price:7.5},
{id:79,name:"Francisco Evanilson de Lima Barbosa",team:"Bournemouth",teamShort:"BOU",pos:"FWD",price:6},
{id:80,name:"Enes Ünal",team:"Bournemouth",teamShort:"BOU",pos:"FWD",price:5.5},
{id:81,name:"Álvaro Rodríguez",team:"Bournemouth",teamShort:"BOU",pos:"FWD",price:6},
{id:566,name:"António João Pereira de Albuquerque Tavares da Silva",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:5},
{id:573,name:"Juanlu Sánchez",team:"Bournemouth",teamShort:"BOU",pos:"DEF",price:4.5},
{id:82,name:"Caoimhín Kelleher",team:"Brentford",teamShort:"BRE",pos:"GKP",price:5},
{id:83,name:"Hákon Rafn Valdimarsson",team:"Brentford",teamShort:"BRE",pos:"GKP",price:4.5},
{id:84,name:"Nathan Collins",team:"Brentford",teamShort:"BRE",pos:"DEF",price:5.5},
{id:85,name:"Sepp van den Berg",team:"Brentford",teamShort:"BRE",pos:"DEF",price:5},
{id:86,name:"Keane Lewis-Potter",team:"Brentford",teamShort:"BRE",pos:"MID",price:5.5},
{id:87,name:"Kristoffer Ajer",team:"Brentford",teamShort:"BRE",pos:"DEF",price:4.5},
{id:88,name:"Michael Kayode",team:"Brentford",teamShort:"BRE",pos:"DEF",price:4.5},
{id:89,name:"Rico Henry",team:"Brentford",teamShort:"BRE",pos:"DEF",price:4.5},
{id:90,name:"Aaron Hickey",team:"Brentford",teamShort:"BRE",pos:"DEF",price:4.5},
{id:91,name:"Ethan Pinnock",team:"Brentford",teamShort:"BRE",pos:"DEF",price:4.5},
{id:92,name:"Kim Ji-soo",team:"Brentford",teamShort:"BRE",pos:"DEF",price:4.5},
{id:93,name:"Jannik Schuster",team:"Brentford",teamShort:"BRE",pos:"DEF",price:4.5},
{id:94,name:"Kevin Schade",team:"Brentford",teamShort:"BRE",pos:"MID",price:6},
{id:95,name:"Dango Ouattara",team:"Brentford",teamShort:"BRE",pos:"MID",price:6.5},
{id:96,name:"Mikkel Damsgaard",team:"Brentford",teamShort:"BRE",pos:"MID",price:5.5},
{id:97,name:"Mathias Jensen",team:"Brentford",teamShort:"BRE",pos:"MID",price:5.5},
{id:98,name:"Vitaly Janelt",team:"Brentford",teamShort:"BRE",pos:"MID",price:5},
{id:99,name:"Antoni Milambo",team:"Brentford",teamShort:"BRE",pos:"MID",price:5},
{id:100,name:"Fábio Freitas Gouveia Carvalho",team:"Brentford",teamShort:"BRE",pos:"MID",price:5},
{id:102,name:"Yehor Yarmoliuk",team:"Brentford",teamShort:"BRE",pos:"MID",price:5},
{id:103,name:"Josh Dasilva",team:"Brentford",teamShort:"BRE",pos:"MID",price:5},
{id:105,name:"Jaidon Anthony",team:"Brentford",teamShort:"BRE",pos:"MID",price:6},
{id:106,name:"Igor Thiago Nascimento Rodrigues",team:"Brentford",teamShort:"BRE",pos:"FWD",price:8},
{id:107,name:"Kaye Furo",team:"Brentford",teamShort:"BRE",pos:"FWD",price:4.5},
{id:108,name:"Callum Wilson",team:"Brentford",teamShort:"BRE",pos:"FWD",price:5.5},
{id:565,name:"Mamadou Sangaré",team:"Brentford",teamShort:"BRE",pos:"MID",price:5.5},
{id:109,name:"Bart Verbruggen",team:"Brighton",teamShort:"BHA",pos:"GKP",price:4.5},
{id:111,name:"Jason Steele",team:"Brighton",teamShort:"BHA",pos:"GKP",price:4},
{id:113,name:"Ferdi Kadıoğlu",team:"Brighton",teamShort:"BHA",pos:"DEF",price:4.5},
{id:114,name:"Olivier Boscagli",team:"Brighton",teamShort:"BHA",pos:"DEF",price:4.5},
{id:115,name:"Maxim De Cuyper",team:"Brighton",teamShort:"BHA",pos:"DEF",price:4.5},
{id:116,name:"Lewis Dunk",team:"Brighton",teamShort:"BHA",pos:"DEF",price:4.5},
{id:117,name:"Diego Coppola",team:"Brighton",teamShort:"BHA",pos:"DEF",price:4.5},
{id:118,name:"Igor Julio dos Santos de Paulo",team:"Brighton",teamShort:"BHA",pos:"DEF",price:4.5},
{id:119,name:"João Pedro Loureiro da Costa",team:"Brighton",teamShort:"BHA",pos:"DEF",price:4.5},
{id:120,name:"Michael Svoboda",team:"Brighton",teamShort:"BHA",pos:"DEF",price:5},
{id:121,name:"Mitoma Kaoru",team:"Brighton",teamShort:"BHA",pos:"MID",price:6},
{id:122,name:"Yankuba Minteh",team:"Brighton",teamShort:"BHA",pos:"MID",price:6},
{id:123,name:"Jack Hinshelwood",team:"Brighton",teamShort:"BHA",pos:"MID",price:6},
{id:124,name:"Pascal Groß",team:"Brighton",teamShort:"BHA",pos:"MID",price:5.5},
{id:125,name:"Georginio Rutter",team:"Brighton",teamShort:"BHA",pos:"FWD",price:5.5},
{id:126,name:"Matt O'Riley",team:"Brighton",teamShort:"BHA",pos:"MID",price:5.5},
{id:127,name:"Diego Gómez Amarilla",team:"Brighton",teamShort:"BHA",pos:"MID",price:5},
{id:128,name:"Facundo Buonanotte",team:"Brighton",teamShort:"BHA",pos:"MID",price:5},
{id:129,name:"Yasin Ayari",team:"Brighton",teamShort:"BHA",pos:"MID",price:5.5},
{id:130,name:"Mats Wieffer",team:"Brighton",teamShort:"BHA",pos:"DEF",price:5},
{id:131,name:"Carlos Baleba",team:"Brighton",teamShort:"BHA",pos:"MID",price:5},
{id:132,name:"Harry Howell",team:"Brighton",teamShort:"BHA",pos:"MID",price:4.5},
{id:133,name:"Tom Watson",team:"Brighton",teamShort:"BHA",pos:"MID",price:5},
{id:134,name:"Nehemiah Oriola",team:"Brighton",teamShort:"BHA",pos:"MID",price:4.5},
{id:135,name:"Zadok Yohanna",team:"Brighton",teamShort:"BHA",pos:"MID",price:5},
{id:137,name:"Stefanos Tzimas",team:"Brighton",teamShort:"BHA",pos:"FWD",price:5.5},
{id:138,name:"Charalampos Kostoulas",team:"Brighton",teamShort:"BHA",pos:"FWD",price:5.5},
{id:139,name:"Evan Ferguson",team:"Brighton",teamShort:"BHA",pos:"FWD",price:5},
{id:328,name:"Pascal Struijk",team:"Brighton",teamShort:"BHA",pos:"DEF",price:5},
{id:504,name:"Luka Vušković",team:"Brighton",teamShort:"BHA",pos:"DEF",price:5},
{id:40,name:"Morgan Rogers",team:"Chelsea",teamShort:"CHE",pos:"MID",price:7.5},
{id:101,name:"Jordan Henderson",team:"Chelsea",teamShort:"CHE",pos:"MID",price:5},
{id:136,name:"Danny Welbeck",team:"Chelsea",teamShort:"CHE",pos:"FWD",price:6},
{id:140,name:"Robert Lynch Sánchez",team:"Chelsea",teamShort:"CHE",pos:"GKP",price:5},
{id:141,name:"Filip Jörgensen",team:"Chelsea",teamShort:"CHE",pos:"GKP",price:5},
{id:142,name:"Reece James",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:5.5},
{id:143,name:"Trevoh Chalobah",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:5.5},
{id:144,name:"Malo Gusto",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:5},
{id:145,name:"Wesley Fofana",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:5},
{id:146,name:"Benoît Badiashile Mukinayi",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:4.5},
{id:147,name:"Tosin Adarabioyo",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:4.5},
{id:148,name:"Jorrel Hato",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:4.5},
{id:149,name:"Levi Samuels Colwill",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:5},
{id:150,name:"Mamadou Sarr",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:4.5},
{id:151,name:"Josh Acheampong",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:4.5},
{id:152,name:"Marco Palestra",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:5.5},
{id:153,name:"Axel Disasi",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:4.5},
{id:154,name:"Cole Palmer",team:"Chelsea",teamShort:"CHE",pos:"MID",price:9.5},
{id:155,name:"Enzo Fernández",team:"Chelsea",teamShort:"CHE",pos:"MID",price:7},
{id:156,name:"Pedro Lomba Neto",team:"Chelsea",teamShort:"CHE",pos:"MID",price:6.5},
{id:157,name:"Estêvão Almeida de Oliveira Gonçalves",team:"Chelsea",teamShort:"CHE",pos:"MID",price:6.5},
{id:158,name:"Jamie Bynoe-Gittens",team:"Chelsea",teamShort:"CHE",pos:"MID",price:6},
{id:159,name:"Moisés Caicedo Corozo",team:"Chelsea",teamShort:"CHE",pos:"MID",price:5.5},
{id:161,name:"Roméo Lavia",team:"Chelsea",teamShort:"CHE",pos:"MID",price:5},
{id:163,name:"Dário Luís Essugo",team:"Chelsea",teamShort:"CHE",pos:"MID",price:4.5},
{id:164,name:"Geovany Quenda",team:"Chelsea",teamShort:"CHE",pos:"MID",price:5.5},
{id:165,name:"João Pedro Junqueira de Jesus",team:"Chelsea",teamShort:"CHE",pos:"FWD",price:7.5},
{id:166,name:"Nicolas Jackson",team:"Chelsea",teamShort:"CHE",pos:"FWD",price:6.5},
{id:167,name:"Liam Delap",team:"Chelsea",teamShort:"CHE",pos:"FWD",price:5.5},
{id:168,name:"Marc Guiu Paz",team:"Chelsea",teamShort:"CHE",pos:"FWD",price:5},
{id:169,name:"Shumaira Mheuka",team:"Chelsea",teamShort:"CHE",pos:"FWD",price:4.5},
{id:170,name:"Emmanuel Emegha",team:"Chelsea",teamShort:"CHE",pos:"FWD",price:5},
{id:200,name:"Maxence Lacroix",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:6},
{id:560,name:"Mike Penders",team:"Chelsea",teamShort:"CHE",pos:"GKP",price:4.5},
{id:561,name:"Aaron Anselmino",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:4.5},
{id:568,name:"Valentín Barco",team:"Chelsea",teamShort:"CHE",pos:"MID",price:5.5},
{id:578,name:"Mykhailo Mudryk",team:"Chelsea",teamShort:"CHE",pos:"MID",price:5.5},
{id:583,name:"Pep Chavarría",team:"Chelsea",teamShort:"CHE",pos:"DEF",price:5},
{id:104,name:"Frank Onyeka",team:"Coventry City",teamShort:"COV",pos:"MID",price:5},
{id:110,name:"Carl Rushworth",team:"Coventry City",teamShort:"COV",pos:"GKP",price:4.5},
{id:171,name:"Oliver Dovin",team:"Coventry City",teamShort:"COV",pos:"GKP",price:4},
{id:172,name:"Ben Wilson",team:"Coventry City",teamShort:"COV",pos:"GKP",price:4.5},
{id:173,name:"Bobby Thomas",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:174,name:"Liam Kitching",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:175,name:"Milan van Ewijk",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:176,name:"Jay Dasilva",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:177,name:"Kaine Kesler-Hayden",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:178,name:"Jake Bidwell",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:179,name:"Joel Latibeaudiere",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:180,name:"Luke Woolfenden",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:181,name:"Miguel Brau",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:182,name:"Aurèle Amenda",team:"Coventry City",teamShort:"COV",pos:"DEF",price:4},
{id:183,name:"Jack Rudoni",team:"Coventry City",teamShort:"COV",pos:"MID",price:5},
{id:184,name:"Matt Grimes",team:"Coventry City",teamShort:"COV",pos:"MID",price:5},
{id:185,name:"Tatsuhiro Sakamoto",team:"Coventry City",teamShort:"COV",pos:"MID",price:5},
{id:186,name:"Ephron Mason-Clark",team:"Coventry City",teamShort:"COV",pos:"MID",price:5.5},
{id:187,name:"Josh Eccles",team:"Coventry City",teamShort:"COV",pos:"MID",price:5},
{id:188,name:"Victor Torp",team:"Coventry City",teamShort:"COV",pos:"MID",price:5.5},
{id:189,name:"George Shepherd",team:"Coventry City",teamShort:"COV",pos:"MID",price:4.5},
{id:190,name:"Loum Tchaouna",team:"Coventry City",teamShort:"COV",pos:"MID",price:5.5},
{id:191,name:"Raphael Borges Rodrigues",team:"Coventry City",teamShort:"COV",pos:"MID",price:4.5},
{id:192,name:"Kaine Andrews",team:"Coventry City",teamShort:"COV",pos:"MID",price:4.5},
{id:193,name:"Haji Wright",team:"Coventry City",teamShort:"COV",pos:"FWD",price:5.5},
{id:194,name:"Brandon Thomas-Asante",team:"Coventry City",teamShort:"COV",pos:"FWD",price:5},
{id:195,name:"Ellis Simms",team:"Coventry City",teamShort:"COV",pos:"FWD",price:5},
{id:196,name:"Jahnoah Markelo",team:"Coventry City",teamShort:"COV",pos:"FWD",price:5},
{id:197,name:"Norman Bassette",team:"Coventry City",teamShort:"COV",pos:"FWD",price:4.5},
{id:575,name:"Caleb Yirenkyi",team:"Coventry City",teamShort:"COV",pos:"MID",price:5},
{id:584,name:"Gustavo Hamer",team:"Coventry City",teamShort:"COV",pos:"MID",price:5.5},
{id:42,name:"Evann Guessand",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5.5},
{id:198,name:"Dean Henderson",team:"Crystal Palace",teamShort:"CRY",pos:"GKP",price:5},
{id:199,name:"Walter Benítez",team:"Crystal Palace",teamShort:"CRY",pos:"GKP",price:4.5},
{id:201,name:"Daniel Muñoz Mejía",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:5.5},
{id:202,name:"Chris Richards",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:5},
{id:203,name:"Jaydee Canvot",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:5},
{id:204,name:"Tyrick Mitchell",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:4.5},
{id:205,name:"Borna Sosa",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:4.5},
{id:206,name:"Chadi Riad Dnanou",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:4.5},
{id:207,name:"Oscar Mingueza",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:4.5},
{id:208,name:"Ismaïla Sarr",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:6.5},
{id:210,name:"Adam Wharton",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5.5},
{id:211,name:"Yéremy Pino Santos",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5.5},
{id:212,name:"Will Hughes",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:4.5},
{id:213,name:"Jefferson Lerma Solís",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5},
{id:214,name:"Daichi Kamada",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5},
{id:215,name:"Justin Devenny",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5},
{id:216,name:"Romain Esse",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5},
{id:217,name:"Matheus França de Oliveira",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5},
{id:218,name:"Cheick Doucouré",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5},
{id:219,name:"Jesurun Rak-Sakyi",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5},
{id:220,name:"Rio Cardines",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:4.5},
{id:221,name:"Joél Drakes-Thomas",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:4.5},
{id:222,name:"Jørgen Strand Larsen",team:"Crystal Palace",teamShort:"CRY",pos:"FWD",price:6},
{id:223,name:"Jean-Philippe Mateta",team:"Crystal Palace",teamShort:"CRY",pos:"FWD",price:6.5},
{id:224,name:"Eddie Nketiah",team:"Crystal Palace",teamShort:"CRY",pos:"FWD",price:5.5},
{id:225,name:"Christantus Uche",team:"Crystal Palace",teamShort:"CRY",pos:"FWD",price:5},
{id:241,name:"Dwight McNeil",team:"Crystal Palace",teamShort:"CRY",pos:"MID",price:5.5},
{id:555,name:"Remi Matthews",team:"Crystal Palace",teamShort:"CRY",pos:"GKP",price:4},
{id:577,name:"Takehiro Tomiyasu",team:"Crystal Palace",teamShort:"CRY",pos:"DEF",price:4.5},
{id:21,name:"Christian Nørgaard",team:"Everton",teamShort:"EVE",pos:"MID",price:5},
{id:209,name:"Brennan Johnson",team:"Everton",teamShort:"EVE",pos:"MID",price:6},
{id:226,name:"Jordan Pickford",team:"Everton",teamShort:"EVE",pos:"GKP",price:5.5},
{id:227,name:"Mark Travers",team:"Everton",teamShort:"EVE",pos:"GKP",price:5},
{id:228,name:"Tom King",team:"Everton",teamShort:"EVE",pos:"GKP",price:4.5},
{id:229,name:"James Tarkowski",team:"Everton",teamShort:"EVE",pos:"DEF",price:6},
{id:230,name:"Jarrad Branthwaite",team:"Everton",teamShort:"EVE",pos:"DEF",price:5.5},
{id:231,name:"Michael Keane",team:"Everton",teamShort:"EVE",pos:"DEF",price:5},
{id:232,name:"Jake O'Brien",team:"Everton",teamShort:"EVE",pos:"DEF",price:5},
{id:233,name:"Vitalii Mykolenko",team:"Everton",teamShort:"EVE",pos:"DEF",price:4.5},
{id:234,name:"Nathan Patterson",team:"Everton",teamShort:"EVE",pos:"DEF",price:4.5},
{id:235,name:"Adam Aznou",team:"Everton",teamShort:"EVE",pos:"DEF",price:4},
{id:236,name:"Kiernan Dewsbury-Hall",team:"Everton",teamShort:"EVE",pos:"MID",price:6.5},
{id:237,name:"Iliman Ndiaye",team:"Everton",teamShort:"EVE",pos:"MID",price:6},
{id:239,name:"James Garner",team:"Everton",teamShort:"EVE",pos:"MID",price:6},
{id:240,name:"Tim Iroegbunam",team:"Everton",teamShort:"EVE",pos:"MID",price:5},
{id:242,name:"Tyrique George",team:"Everton",teamShort:"EVE",pos:"MID",price:5.5},
{id:243,name:"Carlos Alcaraz Durán",team:"Everton",teamShort:"EVE",pos:"MID",price:5},
{id:244,name:"Harrison Armstrong",team:"Everton",teamShort:"EVE",pos:"MID",price:5},
{id:245,name:"Tyler Dibling",team:"Everton",teamShort:"EVE",pos:"MID",price:5.5},
{id:246,name:"Merlin Röhl",team:"Everton",teamShort:"EVE",pos:"MID",price:5},
{id:247,name:"Hayden Hackney",team:"Everton",teamShort:"EVE",pos:"MID",price:5.5},
{id:248,name:"Norberto Bercique Gomes Betuncal",team:"Everton",teamShort:"EVE",pos:"FWD",price:5.5},
{id:249,name:"Thierno Barry",team:"Everton",teamShort:"EVE",pos:"FWD",price:5.5},
{id:250,name:"Bernd Leno",team:"Fulham",teamShort:"FUL",pos:"GKP",price:4.5},
{id:251,name:"Benjamin Lecomte",team:"Fulham",teamShort:"FUL",pos:"GKP",price:4},
{id:252,name:"Alfie McNally",team:"Fulham",teamShort:"FUL",pos:"GKP",price:4},
{id:253,name:"Joachim Andersen",team:"Fulham",teamShort:"FUL",pos:"DEF",price:5},
{id:254,name:"Antonee Robinson",team:"Fulham",teamShort:"FUL",pos:"DEF",price:4.5},
{id:255,name:"Jorge Cuenca Barreno",team:"Fulham",teamShort:"FUL",pos:"DEF",price:4.5},
{id:256,name:"Kenny Tete",team:"Fulham",teamShort:"FUL",pos:"DEF",price:4.5},
{id:257,name:"Calvin Bassey",team:"Fulham",teamShort:"FUL",pos:"DEF",price:4.5},
{id:258,name:"Timothy Castagne",team:"Fulham",teamShort:"FUL",pos:"DEF",price:4.5},
{id:261,name:"Alex Iwobi",team:"Fulham",teamShort:"FUL",pos:"MID",price:5.5},
{id:262,name:"Emile Smith Rowe",team:"Fulham",teamShort:"FUL",pos:"MID",price:5.5},
{id:263,name:"Kevin Santos Lopes de Macedo",team:"Fulham",teamShort:"FUL",pos:"MID",price:5.5},
{id:264,name:"Oscar Bobb",team:"Fulham",teamShort:"FUL",pos:"MID",price:5.5},
{id:265,name:"Sander Berge",team:"Fulham",teamShort:"FUL",pos:"MID",price:5},
{id:266,name:"Tom Cairney",team:"Fulham",teamShort:"FUL",pos:"MID",price:5},
{id:268,name:"Josh King",team:"Fulham",teamShort:"FUL",pos:"MID",price:5.5},
{id:269,name:"Ryan Sessegnon",team:"Fulham",teamShort:"FUL",pos:"DEF",price:4.5},
{id:270,name:"Harrison Reed",team:"Fulham",teamShort:"FUL",pos:"MID",price:4.5},
{id:271,name:"Rodrigo Muniz Carvalho",team:"Fulham",teamShort:"FUL",pos:"FWD",price:5.5},
{id:272,name:"Jonah Kusi-Asare",team:"Fulham",teamShort:"FUL",pos:"FWD",price:4.5},
{id:569,name:"Gonzalo García",team:"Fulham",teamShort:"FUL",pos:"FWD",price:6},
{id:570,name:"César Palacios",team:"Fulham",teamShort:"FUL",pos:"MID",price:5.5},
{id:580,name:"Shea Charles",team:"Fulham",teamShort:"FUL",pos:"MID",price:5},
{id:273,name:"Dillon Phillips",team:"Hull City",teamShort:"HUL",pos:"GKP",price:4},
{id:274,name:"Jack Butland",team:"Hull City",teamShort:"HUL",pos:"GKP",price:4.5},
{id:275,name:"Harvey Cartwright",team:"Hull City",teamShort:"HUL",pos:"GKP",price:4},
{id:276,name:"Thimothée Lo-Tutala",team:"Hull City",teamShort:"HUL",pos:"GKP",price:4},
{id:277,name:"John Egan",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:278,name:"Charlie Hughes",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:279,name:"Semi Ajayi",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:280,name:"Lewie Coyle",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:281,name:"Cody Drameh",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:282,name:"Ryan Giles",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:283,name:"Matty Jacob",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:284,name:"Cathal McCarthy",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:285,name:"Paddy McNair",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:286,name:"Mohamed Belloumi",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:287,name:"Liam Millar",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:288,name:"Kieran Dowell",team:"Hull City",teamShort:"HUL",pos:"MID",price:4.5},
{id:289,name:"Matt Crooks",team:"Hull City",teamShort:"HUL",pos:"MID",price:4.5},
{id:290,name:"Regan Slater",team:"Hull City",teamShort:"HUL",pos:"MID",price:4.5},
{id:291,name:"Eliot Matazo",team:"Hull City",teamShort:"HUL",pos:"MID",price:4.5},
{id:292,name:"Abdülkadir Ömür",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:293,name:"Abu Kamara",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:294,name:"Óscar Zambrano",team:"Hull City",teamShort:"HUL",pos:"MID",price:4.5},
{id:295,name:"Oli McBurnie",team:"Hull City",teamShort:"HUL",pos:"FWD",price:5.5},
{id:296,name:"David Akintola",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:297,name:"Darko Gyabi",team:"Hull City",teamShort:"HUL",pos:"MID",price:4.5},
{id:298,name:"Enis Destan",team:"Hull City",teamShort:"HUL",pos:"FWD",price:4.5},
{id:299,name:"Mason Burstow",team:"Hull City",teamShort:"HUL",pos:"FWD",price:4.5},
{id:556,name:"Matt Targett",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:563,name:"Hidemasa Morita",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:572,name:"Konstantinos Tzolakis",team:"Hull City",teamShort:"HUL",pos:"GKP",price:4.5},
{id:574,name:"Jens Hjertø-Dahl",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:576,name:"Elliot Stroud",team:"Hull City",teamShort:"HUL",pos:"MID",price:5},
{id:585,name:"Lucas Herrington",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:586,name:"Nobel Mendy",team:"Hull City",teamShort:"HUL",pos:"DEF",price:4},
{id:259,name:"Issa Diop",team:"Ipswich Town",teamShort:"IPS",pos:"DEF",price:4},
{id:267,name:"Saša Lukić",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:300,name:"Christian Walton",team:"Ipswich Town",teamShort:"IPS",pos:"GKP",price:4.5},
{id:301,name:"Alex Palmer",team:"Ipswich Town",teamShort:"IPS",pos:"GKP",price:4},
{id:302,name:"David Button",team:"Ipswich Town",teamShort:"IPS",pos:"GKP",price:4},
{id:303,name:"Cédric Kipré",team:"Ipswich Town",teamShort:"IPS",pos:"DEF",price:4},
{id:304,name:"Dara O'Shea",team:"Ipswich Town",teamShort:"IPS",pos:"DEF",price:4},
{id:305,name:"Leif Davis",team:"Ipswich Town",teamShort:"IPS",pos:"DEF",price:4},
{id:306,name:"Jacob Greaves",team:"Ipswich Town",teamShort:"IPS",pos:"DEF",price:4},
{id:307,name:"Ben Johnson",team:"Ipswich Town",teamShort:"IPS",pos:"DEF",price:4},
{id:308,name:"Darnell Furlong",team:"Ipswich Town",teamShort:"IPS",pos:"DEF",price:4},
{id:309,name:"Marcelino Núñez",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:310,name:"Azor Matusiwa",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:311,name:"Wes Burns",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:312,name:"Jack Taylor",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:4.5},
{id:313,name:"Jack Clarke",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5.5},
{id:314,name:"Chiedozie Ogbene",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:315,name:"Abdul Fatawu",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5.5},
{id:316,name:"Emersonn Correia da Silva",team:"Ipswich Town",teamShort:"IPS",pos:"FWD",price:5.5},
{id:317,name:"George Hirst",team:"Ipswich Town",teamShort:"IPS",pos:"FWD",price:5},
{id:318,name:"Jaden Philogene",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5.5},
{id:319,name:"Sam Szmodics",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:320,name:"Chuba Akpom",team:"Ipswich Town",teamShort:"IPS",pos:"FWD",price:5},
{id:321,name:"Sindre Walle Egeli",team:"Ipswich Town",teamShort:"IPS",pos:"FWD",price:4.5},
{id:322,name:"Ali Al-Hamadi",team:"Ipswich Town",teamShort:"IPS",pos:"FWD",price:5},
{id:323,name:"Kasey McAteer",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:4.5},
{id:324,name:"Anis Mehmeti",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:554,name:"Kayne van Oevelen",team:"Ipswich Town",teamShort:"IPS",pos:"GKP",price:4.5},
{id:562,name:"Daizen Maeda",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5.5},
{id:564,name:"Kjell Scherpen",team:"Ipswich Town",teamShort:"IPS",pos:"GKP",price:4.5},
{id:571,name:"Florentino Ibrain Morris Luís",team:"Ipswich Town",teamShort:"IPS",pos:"MID",price:5},
{id:260,name:"Harry Wilson",team:"Leeds",teamShort:"LEE",pos:"MID",price:6.5},
{id:326,name:"Lucas Estella Perri",team:"Leeds",teamShort:"LEE",pos:"GKP",price:4.5},
{id:327,name:"Jaka Bijol",team:"Leeds",teamShort:"LEE",pos:"DEF",price:5},
{id:329,name:"Joe Rodon",team:"Leeds",teamShort:"LEE",pos:"DEF",price:4.5},
{id:330,name:"Jayden Bogle",team:"Leeds",teamShort:"LEE",pos:"DEF",price:4.5},
{id:331,name:"Gabriel Gudmundsson",team:"Leeds",teamShort:"LEE",pos:"DEF",price:4.5},
{id:332,name:"James Justin",team:"Leeds",teamShort:"LEE",pos:"DEF",price:4.5},
{id:333,name:"Sebastiaan Bornauw",team:"Leeds",teamShort:"LEE",pos:"DEF",price:4.5},
{id:334,name:"Tarik Muharemović",team:"Leeds",teamShort:"LEE",pos:"DEF",price:5},
{id:335,name:"Anton Stach",team:"Leeds",teamShort:"LEE",pos:"MID",price:6},
{id:336,name:"Noah Okafor",team:"Leeds",teamShort:"LEE",pos:"MID",price:6},
{id:337,name:"Brenden Aaronson",team:"Leeds",teamShort:"LEE",pos:"MID",price:5.5},
{id:338,name:"Ethan Ampadu",team:"Leeds",teamShort:"LEE",pos:"MID",price:5.5},
{id:339,name:"Sean Longstaff",team:"Leeds",teamShort:"LEE",pos:"MID",price:5},
{id:340,name:"Joe Gelhardt",team:"Leeds",teamShort:"LEE",pos:"MID",price:5},
{id:341,name:"Wilfried Gnonto",team:"Leeds",teamShort:"LEE",pos:"MID",price:5},
{id:342,name:"Jack Harrison",team:"Leeds",teamShort:"LEE",pos:"MID",price:5},
{id:343,name:"Daniel James",team:"Leeds",teamShort:"LEE",pos:"MID",price:5},
{id:344,name:"Ilia Gruev",team:"Leeds",teamShort:"LEE",pos:"MID",price:5},
{id:345,name:"Tanaka Ao",team:"Leeds",teamShort:"LEE",pos:"MID",price:5},
{id:346,name:"Dominic Calvert-Lewin",team:"Leeds",teamShort:"LEE",pos:"FWD",price:6},
{id:347,name:"Lukas Nmecha",team:"Leeds",teamShort:"LEE",pos:"FWD",price:5.5},
{id:348,name:"Joël Piroe",team:"Leeds",teamShort:"LEE",pos:"FWD",price:5},
{id:349,name:"Mateo Joseph Fernández-Regatillo",team:"Leeds",teamShort:"LEE",pos:"FWD",price:4.5},
{id:385,name:"James Trafford",team:"Leeds",teamShort:"LEE",pos:"GKP",price:5},
{id:350,name:"Alisson Becker",team:"Liverpool",teamShort:"LIV",pos:"GKP",price:5.5},
{id:351,name:"Giorgi Mamardashvili",team:"Liverpool",teamShort:"LIV",pos:"GKP",price:5},
{id:352,name:"Freddie Woodman",team:"Liverpool",teamShort:"LIV",pos:"GKP",price:4},
{id:353,name:"Armin Pecsi",team:"Liverpool",teamShort:"LIV",pos:"GKP",price:4},
{id:354,name:"Vitezslav Jaros",team:"Liverpool",teamShort:"LIV",pos:"GKP",price:4},
{id:355,name:"Harvey Davies",team:"Liverpool",teamShort:"LIV",pos:"GKP",price:4},
{id:356,name:"Virgil van Dijk",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:6.5},
{id:357,name:"Jeremie Frimpong",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:5.5},
{id:358,name:"Milos Kerkez",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:5.5},
{id:359,name:"Joe Gomez",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:5},
{id:360,name:"Conor Bradley",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:5},
{id:361,name:"Wellity Lucky",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:4},
{id:362,name:"Jeremy Jacquet",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:5},
{id:363,name:"Giovanni Leoni",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:4},
{id:364,name:"Kostas Tsimikas",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:5},
{id:365,name:"Calvin Ramsay",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:4},
{id:366,name:"Florian Wirtz",team:"Liverpool",teamShort:"LIV",pos:"MID",price:7.5},
{id:367,name:"Cody Gakpo",team:"Liverpool",teamShort:"LIV",pos:"MID",price:7},
{id:368,name:"Dominik Szoboszlai",team:"Liverpool",teamShort:"LIV",pos:"MID",price:7},
{id:369,name:"Rio Ngumoha",team:"Liverpool",teamShort:"LIV",pos:"MID",price:6},
{id:370,name:"Federico Chiesa",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5.5},
{id:371,name:"Ryan Gravenberch",team:"Liverpool",teamShort:"LIV",pos:"MID",price:6},
{id:372,name:"Alexis Mac Allister",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5.5},
{id:373,name:"Curtis Jones",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5.5},
{id:374,name:"Endo Wataru",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5},
{id:375,name:"Trey Nyoni",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5},
{id:376,name:"Stefan Bajčetić Maquieira",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5},
{id:377,name:"Victor Munoz",team:"Liverpool",teamShort:"LIV",pos:"MID",price:6.5},
{id:378,name:"James McConnell",team:"Liverpool",teamShort:"LIV",pos:"MID",price:4.5},
{id:379,name:"Alexander Isak",team:"Liverpool",teamShort:"LIV",pos:"FWD",price:9},
{id:380,name:"Hugo Ekitiké",team:"Liverpool",teamShort:"LIV",pos:"FWD",price:7.5},
{id:381,name:"Lewis Koumas",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5},
{id:382,name:"Jayden Danns",team:"Liverpool",teamShort:"LIV",pos:"FWD",price:4.5},
{id:383,name:"Harvey Elliott",team:"Liverpool",teamShort:"LIV",pos:"MID",price:5.5},
{id:579,name:"Ronald Araujo",team:"Liverpool",teamShort:"LIV",pos:"DEF",price:5.5},
{id:238,name:"Jack Grealish",team:"Man City",teamShort:"MCI",pos:"MID",price:6.5},
{id:384,name:"Gianluigi Donnarumma",team:"Man City",teamShort:"MCI",pos:"GKP",price:5.5},
{id:386,name:"Marcus Bettinelli",team:"Man City",teamShort:"MCI",pos:"GKP",price:4.5},
{id:387,name:"Nico O'Reilly",team:"Man City",teamShort:"MCI",pos:"DEF",price:6.5},
{id:388,name:"Marc Guéhi",team:"Man City",teamShort:"MCI",pos:"DEF",price:6},
{id:389,name:"Matheus Nunes",team:"Man City",teamShort:"MCI",pos:"DEF",price:6},
{id:390,name:"Rúben dos Santos Gato Alves Dias",team:"Man City",teamShort:"MCI",pos:"DEF",price:5.5},
{id:391,name:"Joško Gvardiol",team:"Man City",teamShort:"MCI",pos:"DEF",price:5.5},
{id:392,name:"Rayan Aït-Nouri",team:"Man City",teamShort:"MCI",pos:"DEF",price:5.5},
{id:393,name:"Abdukodir Khusanov",team:"Man City",teamShort:"MCI",pos:"DEF",price:5.5},
{id:394,name:"Max Alleyne",team:"Man City",teamShort:"MCI",pos:"DEF",price:5},
{id:395,name:"Rico Lewis",team:"Man City",teamShort:"MCI",pos:"DEF",price:4.5},
{id:396,name:"Vitor de Oliveira Nunes dos Reis",team:"Man City",teamShort:"MCI",pos:"DEF",price:4.5},
{id:397,name:"Antoine Semenyo",team:"Man City",teamShort:"MCI",pos:"MID",price:8.5},
{id:398,name:"Phil Foden",team:"Man City",teamShort:"MCI",pos:"MID",price:7},
{id:399,name:"Rayan Cherki",team:"Man City",teamShort:"MCI",pos:"MID",price:7.5},
{id:400,name:"Jérémy Doku",team:"Man City",teamShort:"MCI",pos:"MID",price:7.5},
{id:401,name:"Omar Marmoush",team:"Man City",teamShort:"MCI",pos:"FWD",price:7},
{id:402,name:"Rodrigo 'Rodri' Hernandez Cascante",team:"Man City",teamShort:"MCI",pos:"MID",price:6.5},
{id:403,name:"Sávio Moreira de Oliveira",team:"Man City",teamShort:"MCI",pos:"MID",price:6.5},
{id:404,name:"Tijjani Reijnders",team:"Man City",teamShort:"MCI",pos:"MID",price:6},
{id:405,name:"Nico González Iglesias",team:"Man City",teamShort:"MCI",pos:"MID",price:5.5},
{id:406,name:"Mateo Kovačić",team:"Man City",teamShort:"MCI",pos:"MID",price:5.5},
{id:407,name:"Claudio Echeverri",team:"Man City",teamShort:"MCI",pos:"MID",price:5},
{id:408,name:"Kalvin Phillips",team:"Man City",teamShort:"MCI",pos:"MID",price:5},
{id:409,name:"Divine Mukasa",team:"Man City",teamShort:"MCI",pos:"MID",price:4.5},
{id:410,name:"Jeremy Monga",team:"Man City",teamShort:"MCI",pos:"MID",price:5},
{id:411,name:"Erling Haaland",team:"Man City",teamShort:"MCI",pos:"FWD",price:15.5},
{id:481,name:"Elliot Anderson",team:"Man City",teamShort:"MCI",pos:"MID",price:6.5},
{id:587,name:"Gerónimo Rulli",team:"Man City",teamShort:"MCI",pos:"GKP",price:5},
{id:43,name:"Youri Tielemans",team:"Man Utd",teamShort:"MUN",pos:"MID",price:6},
{id:162,name:"Andrey Nascimento dos Santos",team:"Man Utd",teamShort:"MUN",pos:"MID",price:5},
{id:325,name:"Karl Darlow",team:"Man Utd",teamShort:"MUN",pos:"GKP",price:4.5},
{id:412,name:"Senne Lammens",team:"Man Utd",teamShort:"MUN",pos:"GKP",price:5},
{id:413,name:"Altay Bayındır",team:"Man Utd",teamShort:"MUN",pos:"GKP",price:4.5},
{id:414,name:"Tom Heaton",team:"Man Utd",teamShort:"MUN",pos:"GKP",price:4},
{id:415,name:"Patrick Dorgu",team:"Man Utd",teamShort:"MUN",pos:"MID",price:6},
{id:416,name:"Matthijs de Ligt",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:5},
{id:417,name:"Diogo Dalot Teixeira",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:5},
{id:418,name:"Harry Maguire",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:5},
{id:419,name:"Lisandro Martínez",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:5},
{id:420,name:"Leny Yoro",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:5},
{id:421,name:"Ayden Heaven",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:4.5},
{id:422,name:"Noussair Mazraoui",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:4.5},
{id:423,name:"Luke Shaw",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:4.5},
{id:424,name:"Harry Amass",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:4},
{id:425,name:"Tyler Fredricson",team:"Man Utd",teamShort:"MUN",pos:"DEF",price:4},
{id:426,name:"Bruno Borges Fernandes",team:"Man Utd",teamShort:"MUN",pos:"MID",price:12},
{id:427,name:"Bryan Mbeumo",team:"Man Utd",teamShort:"MUN",pos:"MID",price:8},
{id:428,name:"Matheus Santos Carneiro da Cunha",team:"Man Utd",teamShort:"MUN",pos:"MID",price:8},
{id:429,name:"Marcus Rashford",team:"Man Utd",teamShort:"MUN",pos:"MID",price:7},
{id:430,name:"Mason Mount",team:"Man Utd",teamShort:"MUN",pos:"MID",price:5.5},
{id:431,name:"Amad Diallo",team:"Man Utd",teamShort:"MUN",pos:"MID",price:6},
{id:432,name:"Kobbie Mainoo",team:"Man Utd",teamShort:"MUN",pos:"MID",price:5.5},
{id:433,name:"Manuel Ugarte Ribeiro",team:"Man Utd",teamShort:"MUN",pos:"MID",price:5},
{id:434,name:"Jack Fletcher",team:"Man Utd",teamShort:"MUN",pos:"MID",price:5},
{id:435,name:"Shea Lacey",team:"Man Utd",teamShort:"MUN",pos:"MID",price:5},
{id:436,name:"Toby Collyer",team:"Man Utd",teamShort:"MUN",pos:"MID",price:5},
{id:437,name:"Bendito Mantato",team:"Man Utd",teamShort:"MUN",pos:"MID",price:4.5},
{id:438,name:"Tyler Fletcher",team:"Man Utd",teamShort:"MUN",pos:"MID",price:4.5},
{id:439,name:"Benjamin Sesko",team:"Man Utd",teamShort:"MUN",pos:"FWD",price:7},
{id:440,name:"Joshua Zirkzee",team:"Man Utd",teamShort:"MUN",pos:"FWD",price:5.5},
{id:441,name:"Chido Obi",team:"Man Utd",teamShort:"MUN",pos:"FWD",price:4.5},
{id:442,name:"Nick Pope",team:"Newcastle",teamShort:"NEW",pos:"GKP",price:5},
{id:443,name:"Mark Gillespie",team:"Newcastle",teamShort:"NEW",pos:"GKP",price:4.5},
{id:444,name:"Ewen Jaouen",team:"Newcastle",teamShort:"NEW",pos:"GKP",price:4.5},
{id:445,name:"Malick Thiaw",team:"Newcastle",teamShort:"NEW",pos:"DEF",price:5},
{id:446,name:"Fabian Schär",team:"Newcastle",teamShort:"NEW",pos:"DEF",price:5},
{id:447,name:"Sven Botman",team:"Newcastle",teamShort:"NEW",pos:"DEF",price:5},
{id:448,name:"Dan Burn",team:"Newcastle",teamShort:"NEW",pos:"DEF",price:5},
{id:449,name:"Lewis Hall",team:"Newcastle",teamShort:"NEW",pos:"DEF",price:5},
{id:450,name:"Tino Livramento",team:"Newcastle",teamShort:"NEW",pos:"DEF",price:5},
{id:451,name:"Alex Murphy",team:"Newcastle",teamShort:"NEW",pos:"DEF",price:4},
{id:453,name:"Harvey Barnes",team:"Newcastle",teamShort:"NEW",pos:"MID",price:6},
{id:454,name:"Anthony Elanga",team:"Newcastle",teamShort:"NEW",pos:"MID",price:6},
{id:456,name:"Jacob Ramsey",team:"Newcastle",teamShort:"NEW",pos:"MID",price:5},
{id:457,name:"Jacob Murphy",team:"Newcastle",teamShort:"NEW",pos:"MID",price:6},
{id:458,name:"Joelinton Cássio Apolinário de Lira",team:"Newcastle",teamShort:"NEW",pos:"MID",price:5.5},
{id:459,name:"Lewis Miley",team:"Newcastle",teamShort:"NEW",pos:"MID",price:5.5},
{id:460,name:"Joe Willock",team:"Newcastle",teamShort:"NEW",pos:"MID",price:5},
{id:461,name:"Bazoumana Touré",team:"Newcastle",teamShort:"NEW",pos:"MID",price:6},
{id:462,name:"Sean Steur",team:"Newcastle",teamShort:"NEW",pos:"MID",price:5},
{id:463,name:"Nick Woltemade",team:"Newcastle",teamShort:"NEW",pos:"FWD",price:6},
{id:464,name:"Yoane Wissa",team:"Newcastle",teamShort:"NEW",pos:"FWD",price:6},
{id:465,name:"William Osula",team:"Newcastle",teamShort:"NEW",pos:"FWD",price:6},
{id:466,name:"Sean Neave",team:"Newcastle",teamShort:"NEW",pos:"FWD",price:4.5},
{id:559,name:"Aladji Bamba",team:"Newcastle",teamShort:"NEW",pos:"MID",price:5},
{id:567,name:"Lukás Hornícek",team:"Newcastle",teamShort:"NEW",pos:"GKP",price:5},
{id:467,name:"Matz Sels",team:"Nott'm Forest",teamShort:"NFO",pos:"GKP",price:5},
{id:468,name:"John Victor Maciel Furtado",team:"Nott'm Forest",teamShort:"NFO",pos:"GKP",price:4.5},
{id:469,name:"Neco Williams",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:5},
{id:470,name:"Felipe Rodrigues da Silva",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:5},
{id:471,name:"Nikola Milenković",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:5.5},
{id:472,name:"Murillo Costa dos Santos",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:5.5},
{id:473,name:"Ola Aina",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:4.5},
{id:474,name:"Jair Paula da Cunha Filho",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:4.5},
{id:475,name:"Nicolò Savona",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:4.5},
{id:476,name:"Omar Richards",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:4},
{id:477,name:"Zach Abbott",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:4},
{id:478,name:"Luca Netz",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:4.5},
{id:479,name:"Tyler Bindon",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:4},
{id:480,name:"Morgan Gibbs-White",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:8},
{id:482,name:"Callum Hudson-Odoi",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:6},
{id:483,name:"Dan Ndoye",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:5.5},
{id:484,name:"Omari Hutchinson",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:5.5},
{id:485,name:"Dilane Bakwa",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:5.5},
{id:486,name:"James McAtee",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:5.5},
{id:487,name:"Nicolás Domínguez",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:5},
{id:488,name:"Ibrahim Sangaré",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:5},
{id:489,name:"Ryan Yates",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:4.5},
{id:490,name:"Chris Wood",team:"Nott'm Forest",teamShort:"NFO",pos:"FWD",price:6},
{id:491,name:"Igor Jesus Maciel da Cruz",team:"Nott'm Forest",teamShort:"NFO",pos:"FWD",price:6},
{id:492,name:"Taiwo Awoniyi",team:"Nott'm Forest",teamShort:"NFO",pos:"FWD",price:5.5},
{id:493,name:"Arnaud Kalimuendo",team:"Nott'm Forest",teamShort:"NFO",pos:"FWD",price:5.5},
{id:558,name:"Xaver Schlager",team:"Nott'm Forest",teamShort:"NFO",pos:"MID",price:5},
{id:581,name:"Ousmane Diomande",team:"Nott'm Forest",teamShort:"NFO",pos:"DEF",price:5.5},
{id:112,name:"Jan Paul van Hecke",team:"Spurs",teamShort:"TOT",pos:"DEF",price:5},
{id:455,name:"Sandro Tonali",team:"Spurs",teamShort:"TOT",pos:"MID",price:5.5},
{id:494,name:"Guglielmo Vicario",team:"Spurs",teamShort:"TOT",pos:"GKP",price:4.5},
{id:495,name:"Brandon Austin",team:"Spurs",teamShort:"TOT",pos:"GKP",price:4},
{id:496,name:"Antonín Kinský",team:"Spurs",teamShort:"TOT",pos:"GKP",price:4.5},
{id:497,name:"Martin Dubravka",team:"Spurs",teamShort:"TOT",pos:"GKP",price:4},
{id:498,name:"Marcos Senesi Barón",team:"Spurs",teamShort:"TOT",pos:"DEF",price:6},
{id:499,name:"Pedro Porro Sauceda",team:"Spurs",teamShort:"TOT",pos:"DEF",price:5.5},
{id:500,name:"Cristian Romero",team:"Spurs",teamShort:"TOT",pos:"DEF",price:5},
{id:501,name:"Kevin Danso",team:"Spurs",teamShort:"TOT",pos:"DEF",price:5},
{id:502,name:"Andrew Robertson",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4.5},
{id:503,name:"Micky van de Ven",team:"Spurs",teamShort:"TOT",pos:"DEF",price:5},
{id:505,name:"Djed Spence",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4.5},
{id:506,name:"Destiny Udogie",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4.5},
{id:507,name:"Ashley Phillips",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4.5},
{id:508,name:"Ben Davies",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4},
{id:509,name:"Jun'ai Byfield",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4},
{id:510,name:"James Rowswell",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4},
{id:511,name:"João Victor de Souza Menezes",team:"Spurs",teamShort:"TOT",pos:"DEF",price:4},
{id:512,name:"Mohammed Kudus",team:"Spurs",teamShort:"TOT",pos:"MID",price:6.5},
{id:513,name:"Xavi Simons",team:"Spurs",teamShort:"TOT",pos:"MID",price:6},
{id:514,name:"Mathys Tel",team:"Spurs",teamShort:"TOT",pos:"MID",price:6},
{id:515,name:"James Maddison",team:"Spurs",teamShort:"TOT",pos:"MID",price:6.5},
{id:516,name:"Rodrigo Bentancur",team:"Spurs",teamShort:"TOT",pos:"MID",price:5.5},
{id:517,name:"Wilson Odobert",team:"Spurs",teamShort:"TOT",pos:"MID",price:5.5},
{id:518,name:"Pape Matar Sarr",team:"Spurs",teamShort:"TOT",pos:"MID",price:5},
{id:519,name:"Conor Gallagher",team:"Spurs",teamShort:"TOT",pos:"MID",price:5.5},
{id:520,name:"Lucas Bergvall",team:"Spurs",teamShort:"TOT",pos:"MID",price:5.5},
{id:521,name:"Dejan Kulusevski",team:"Spurs",teamShort:"TOT",pos:"MID",price:6.5},
{id:522,name:"Archie Gray",team:"Spurs",teamShort:"TOT",pos:"MID",price:5},
{id:523,name:"Mikey Moore",team:"Spurs",teamShort:"TOT",pos:"MID",price:5},
{id:524,name:"Callum Olusesi",team:"Spurs",teamShort:"TOT",pos:"MID",price:4.5},
{id:525,name:"Mateus Fernandes",team:"Spurs",teamShort:"TOT",pos:"MID",price:6},
{id:526,name:"Dominic Solanke-Mitchell",team:"Spurs",teamShort:"TOT",pos:"FWD",price:6},
{id:527,name:"Richarlison de Andrade",team:"Spurs",teamShort:"TOT",pos:"FWD",price:6},
{id:528,name:"Dane Scarlett",team:"Spurs",teamShort:"TOT",pos:"FWD",price:4.5},
{id:529,name:"Robin Roefs",team:"Sunderland",teamShort:"SUN",pos:"GKP",price:5},
{id:530,name:"Anthony Patterson",team:"Sunderland",teamShort:"SUN",pos:"GKP",price:4},
{id:531,name:"Melker Ellborg",team:"Sunderland",teamShort:"SUN",pos:"GKP",price:4.5},
{id:532,name:"Daniel Ballard",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:5},
{id:533,name:"Nordi Mukiele",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:5.5},
{id:534,name:"Trai Hume",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:4.5},
{id:535,name:"Omar Alderete",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:5},
{id:536,name:"Reinildo Mandava",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:4.5},
{id:537,name:"Jenson Seelt",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:4.5},
{id:538,name:"Leo Fuhr Hjelde",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:4},
{id:539,name:"Luke O'Nien",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:4},
{id:540,name:"Arthur Masuaku",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:4},
{id:541,name:"Thomas Meunier",team:"Sunderland",teamShort:"SUN",pos:"DEF",price:4.5},
{id:542,name:"Enzo Le Fée",team:"Sunderland",teamShort:"SUN",pos:"MID",price:6},
{id:543,name:"Habib Diarra",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5.5},
{id:544,name:"Granit Xhaka",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5.5},
{id:545,name:"Noah Sadiki",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5},
{id:546,name:"Simon Adingra",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5},
{id:547,name:"Romaine Mundle",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5},
{id:548,name:"Chris Rigg",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5},
{id:549,name:"Chemsdine Talbi",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5.5},
{id:550,name:"Djiamgone Jocelin Ta Bi",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5},
{id:551,name:"Nilson Angulo",team:"Sunderland",teamShort:"SUN",pos:"MID",price:5},
{id:552,name:"Brian Brobbey",team:"Sunderland",teamShort:"SUN",pos:"FWD",price:6},
{id:553,name:"Wilson Isidor",team:"Sunderland",teamShort:"SUN",pos:"FWD",price:5.5}
];
